### ISSUE TITLE
error when running inference

### ISSUE THREAD

**Issue by avilella** [BioinfoMachineLearning/DProQ#2]
~/DProQ$ /data/miniconda3/envs/DProQ/bin/python3 ./inference.py -c ./examples/6AL0/ -w ./examples/work/ -r ./examples/result
  File "./inference.py", line 79
    continue
    ^
SyntaxError: 'continue' not properly in loop

**Comment by XiaoChen1992** [comment]
Hi, we fixed this bug.

Thanks
